use_frameworks!

platform :ios, '10.0'

target 'ObjectVoice_Example' do
  pod 'ObjectVoice', :path => '../'

  target 'ObjectVoice_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 9.0.1'
  end
end
